minimum_log_level: debug
default_target_host: "www.nuget.org"
cache_probatory_size: 0
cache_resident_size: 10000
listening_port: 4002
prometheus_port: 4004
https: true
http2: false
hash_body: false
response_replacement_strings:
  "nuget": "pouetsuperlongsupersuperlongpouet"
exclude_path_containing:
  - "test."
bypass_path_containing:
  - "/index.json"