minimum_log_level: debug
default_target_host: "www.nuget.org"
listening_port: 4002
prometheus_port: 4004
https: true
http2: false
hash_body: false
response_replacement_strings:
  "nuget": "pouetsuperlongsupersuperlongpouet"
exclude_path_containing:
  - "newtonsoft."
bypass_path_containing:
  - "/index.json"