[package]
name = "risu"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "risu"
path = "src/main.rs"

[[bin]]
name = "demo"
path = "src/demo/main.rs"

[dependencies]
tonic = "0.11"
prost = "0.12"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
bytes = "1.0"

[build-dependencies]
tonic-build = "0.11"
