[package]
name = "cacheus"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cacheus"
path = "src/main.rs"

[lib]
name = "cacheus"

[[test]]
name = "tests"
path = "tests/tests.rs"

[[bench]]
name = "arena_linked_list"
harness = false

[[bench]]
name = "qps"
harness = false

[[bench]]
name = "qps_http"
harness = false

[[example]]
name = "nuget_cache"
harness = false

[dependencies]
hyper = { version = "1.2", features = ["full"] }
hyper-tls = "0.6.0"
tokio = { version = "1", features = ["full"] }
bytes = "1.0"
simplelog = "0.12.2"
log = "0.4.21"
http-body-util = "0.1"
gxhash = "3.1.1"
serde_yaml = "0.9.34"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"
futures = { version = "0.3" }
hyper-util = { version = "0.1", features = ["full"] }
pin-project-lite = "0.2.14"
futures-core = "0.3.30"
prometheus = "0.13"

[dev-dependencies]
tonic = "0.11"
prost = "0.12"
itertools = "0.12.1"
criterion = { version = "0.5.1" }
warp = "0.3"

[build-dependencies]
tonic-build = "0.11"