listening_port: 8080
prometheus_port: 8081
heathcheck_port: 8082
minimum_log_level: info

middlewares:
  - log:
      level: info
      value: 'Cache status: $cache_status, Forward target: $forward_target'
  - add_response_header:
      name: 'X-Cache-Status'
      value: '$cache_status'
  - use_cache:
      cache_name: files
      when:
        status_code_is: 200
  - forward_request:
      scheme: https
      target_host: deviceatlas.com

caches:
  - hybrid:
      name: files
      path: /tmp/cacheus/deviceatlas
      ttl_seconds: 10
      hash_path: false
      hash_query: true
      hash_body: false