name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-feature=+aes"

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test
