name: 'On Version Tag'

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  check:
    name: Check Branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check Branch
      run: |
        git fetch
        BRANCH_NAME=$(git branch -r --contains ${{ github.ref_name }} --format='%(refname:short)')
        BRANCH_NAME=${BRANCH_NAME#*/}
        if [[ "${BRANCH_NAME}" != "main" ]]; then
          echo "This workflow can only be triggered from main branch."
          exit 1
        fi

  push-docker:
    name: Push Docker
    runs-on: ubuntu-latest
    needs: [check]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        shell: bash
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build and Push (Multi-Arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ogxd/cacheus:latest
            ghcr.io/ogxd/cacheus:${{ github.ref_name }}